// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: 'bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948',
    name: 'CollaberaInteropTest',
    user: {
      name: 'user@domain.example',
      type: 'user'
    },
    tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47',
    state: 'Enabled',
    registeredProviders: [],
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_VM_TEST_LOCATION'] = 'eastus';
};

exports.scopes = [[function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/xplatTestGExpressRouteAuth/providers/Microsoft.Network/expressRouteCircuits/xplatExpressRouteA/authorizations?api-version=2015-05-01-preview')
  .reply(200, "{\r\n  \"value\": [\r\n    {\r\n      \"name\": \"xplatExpressRouteAuth\",\r\n      \"id\": \"/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/xplatTestGExpressRouteAuth/providers/Microsoft.Network/expressRouteCircuits/xplatExpressRouteA/authorizations/xplatExpressRouteAuth\",\r\n      \"etag\": \"W/\\\"a4019ec4-3ffb-491f-bdd7-cfbd5acddee2\\\"\",\r\n      \"properties\": {\r\n        \"provisioningState\": \"Succeeded\",\r\n        \"authorizationKey\": \"308201B006092A864886F70D010703A08201A13082019D0201003182014930820145020100302D3019311730150603550403130E6E72702D656E6372797074696F6E021078A0163F01050D9647F47ED7EF267DBC300D06092A864886F70D0101010500048201001C6F597BFEEDDE009180476739A140C7782D9F81C629482CA36F9BBD9BD400AF287BC6CDF662112D5B17E2E3AA17486248080B73D4E781F8616E2AE1D2271900B4EE741E45434E2770C79F66C2169E7FD55EFF42F0002B157B8357DEEEDABF22DC71039E4A1503530EEEB62F2234523C13989A402AD1E943151AA4194B80CA5101E0C16097549CD1BEBE123550E5D4BDCF0E9816239552CA3ECF82C41D69566138156557E10E924B3D23D6FC3E9ACE05720D8F2D0EC656EF3974724F5A0984D4DADCCBA7B9C7399FAC22824C0C0E21767D82A17F20DD462B253DBCC553263EE38E85B2B037ECDAA8253B45104C9B47B8A90F7F228CDFF0E0C33BC0E17A76AE9F304B06092A864886F70D010701301406082A864886F70D03070408A08392E86C15EAFD80283DE51C44037A40B78BAFDB36A4C6FE22BD37AB2D4567645A040928770CC83723F3C37D065C03D914\",\r\n        \"authorizationUseStatus\": \"Available\"\r\n      }\r\n    }\r\n  ],\r\n  \"nextLink\": \"\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '1399',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '3323bbd1-4bed-47b7-983a-385bb717acba',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14995',
  'x-ms-correlation-request-id': '436669b8-d90b-4dcc-b561-0944a2437386',
  'x-ms-routing-request-id': 'SOUTHEASTASIA:20151021T153341Z:436669b8-d90b-4dcc-b561-0944a2437386',
  date: 'Wed, 21 Oct 2015 15:33:41 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/xplatTestGExpressRouteAuth/providers/Microsoft.Network/expressRouteCircuits/xplatExpressRouteA/authorizations?api-version=2015-05-01-preview')
  .reply(200, "{\r\n  \"value\": [\r\n    {\r\n      \"name\": \"xplatExpressRouteAuth\",\r\n      \"id\": \"/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/xplatTestGExpressRouteAuth/providers/Microsoft.Network/expressRouteCircuits/xplatExpressRouteA/authorizations/xplatExpressRouteAuth\",\r\n      \"etag\": \"W/\\\"a4019ec4-3ffb-491f-bdd7-cfbd5acddee2\\\"\",\r\n      \"properties\": {\r\n        \"provisioningState\": \"Succeeded\",\r\n        \"authorizationKey\": \"308201B006092A864886F70D010703A08201A13082019D0201003182014930820145020100302D3019311730150603550403130E6E72702D656E6372797074696F6E021078A0163F01050D9647F47ED7EF267DBC300D06092A864886F70D0101010500048201001C6F597BFEEDDE009180476739A140C7782D9F81C629482CA36F9BBD9BD400AF287BC6CDF662112D5B17E2E3AA17486248080B73D4E781F8616E2AE1D2271900B4EE741E45434E2770C79F66C2169E7FD55EFF42F0002B157B8357DEEEDABF22DC71039E4A1503530EEEB62F2234523C13989A402AD1E943151AA4194B80CA5101E0C16097549CD1BEBE123550E5D4BDCF0E9816239552CA3ECF82C41D69566138156557E10E924B3D23D6FC3E9ACE05720D8F2D0EC656EF3974724F5A0984D4DADCCBA7B9C7399FAC22824C0C0E21767D82A17F20DD462B253DBCC553263EE38E85B2B037ECDAA8253B45104C9B47B8A90F7F228CDFF0E0C33BC0E17A76AE9F304B06092A864886F70D010701301406082A864886F70D03070408A08392E86C15EAFD80283DE51C44037A40B78BAFDB36A4C6FE22BD37AB2D4567645A040928770CC83723F3C37D065C03D914\",\r\n        \"authorizationUseStatus\": \"Available\"\r\n      }\r\n    }\r\n  ],\r\n  \"nextLink\": \"\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '1399',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '3323bbd1-4bed-47b7-983a-385bb717acba',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14995',
  'x-ms-correlation-request-id': '436669b8-d90b-4dcc-b561-0944a2437386',
  'x-ms-routing-request-id': 'SOUTHEASTASIA:20151021T153341Z:436669b8-d90b-4dcc-b561-0944a2437386',
  date: 'Wed, 21 Oct 2015 15:33:41 GMT',
  connection: 'close' });
 return result; }]];